/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banco_de_dados_2_view;

import banco_de_dados_2_beans.Bairro;
import banco_de_dados_2_beans.Cidade;
import banco_de_dados_2_beans.Estado;
import banco_de_dados_2_beans.Logradouro;
import banco_de_dados_2_beans.ObjectsBD;
import banco_de_dados_2_beans.Pais;
import banco_de_dados_2_beans.Pessoas;
import banco_de_dados_2_controller.ControleGenerico;
import banco_de_dados_2_props.TipoObjetoProps;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 *
 * @author Lucas
 */
public class ViewMain extends JFrame {

    private Pessoas pessoa;
    private Logradouro logradouro;
    private Bairro bairro;
    private Cidade cidade;
    private Estado estado;
    private Pais pais;

    private final int CADASTRO = 1;
    private final int ALTERACAO = 2;

    public static JOptionPane dialog = new JOptionPane();

    JScrollPane scroller1 = new JScrollPane(conexao1, JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
    JScrollPane scroller2 = new JScrollPane(conexao2, JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
    JScrollPane scroller3 = new JScrollPane(conexao3, JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
    JScrollPane scroller4 = new JScrollPane(conexao4, JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);

    /**
     * Creates new form ViewMain
     */
    public ViewMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void abreCadastroAuxiliar(String tipoCadastro) {
        ViewCadastroAuxiliar viewCadastroAuxiliar = new ViewCadastroAuxiliar(tipoCadastro, this);
        viewCadastroAuxiliar.setVisible(true);
        viewCadastroAuxiliar.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    public void setSelectObjetct(String tipoObjeto, ObjectsBD objBD) {

        if (objBD != null) {
            switch (tipoObjeto) {
                case "logradouro": {
                    logradouro = new Logradouro();
                    logradouro = (Logradouro) objBD;
                    campoTextoLogradouro.setText(logradouro.getNome());
                }
                break;
                case "bairro": {
                    bairro = new Bairro();
                    bairro = (Bairro) objBD;
                    campoTextoBairro.setText(bairro.getNome());
                }
                break;
                case "cidade": {
                    cidade = new Cidade();
                    cidade = (Cidade) objBD;
                    campoTextoCidade.setText(cidade.getNome());
                }
                break;
                case "estado": {
                    estado = new Estado();
                    estado = (Estado) objBD;
                    campoTextoEstado.setText(estado.getNome());
                }
                break;
                case "pais": {
                    pais = new Pais();
                    pais = (Pais) objBD;
                    campoTextoPais.setText(pais.getNome());
                    break;
                }
                case "pessoas": {
                    pessoa = new Pessoas();
                    pessoa = (Pessoas) objBD;
                    logradouro = pessoa.getLogradouro();
                    bairro = pessoa.getBairro();
                    cidade = pessoa.getCidade();
                    estado = pessoa.getEstado();
                    pais = pessoa.getPais();

                    campoTextoCodigo.setText(String.valueOf(pessoa.getId()));
                    campoTextoNome.setText(pessoa.getNome());
                    campoTextoLogradouro.setText(pessoa.getLogradouro().getNome());
                    campoTextoBairro.setText(pessoa.getPais().getNome());
                    campoTextoCidade.setText(pessoa.getCidade().getNome());
                    campoTextoEstado.setText(pessoa.getEstado().getNome());
                    campoTextoPais.setText(pessoa.getPais().getNome());
                }
                break;
            }
        }
    }

    private boolean validarCampos() {
        /*Validar campos de textos não escritos*/
        return !(campoTextoNome.getText().isEmpty()
                || campoTextoLogradouro.getText().isEmpty()
                || campoTextoBairro.getText().isEmpty()
                || campoTextoCidade.getText().isEmpty()
                || campoTextoEstado.getText().isEmpty()
                || campoTextoPais.getText().isEmpty());
    }

    private boolean validarObjetosNulos(int opcao) {

        /*Se logradouro for nulo será inserido no banco*/
        if (logradouro == null) {
            if (mostraMensagemObjetoNulo(TipoObjetoProps.LOGRADOURO, campoTextoLogradouro.getText())) {
                ControleGenerico.insert(TipoObjetoProps.LOGRADOURO, campoTextoLogradouro.getText(), null);
                ObjectsBD obj = ControleGenerico.select(TipoObjetoProps.LOGRADOURO, campoTextoLogradouro.getText());
                logradouro = (Logradouro) obj;
                if (logradouro == null) {
                    System.out.println("Falha ao recuperar do banco");
                    return false;
                } else {
                    System.out.println("Recuperado do banco com sucesso");
                }
            } else {
                System.out.println("Usuairo optou por não inserir no banco de dados.");
                return false;
            }
        } else {
            System.out.println("logradouro não é nulo.");
        }
        // Fim tratamento de logradouro

        /*Se bairro for nulo será inserido no banco*/
        if (bairro == null) {
            if (mostraMensagemObjetoNulo(TipoObjetoProps.BAIRRO, campoTextoBairro.getText())) {
                ControleGenerico.insert(TipoObjetoProps.BAIRRO, campoTextoBairro.getText(), null);
                ObjectsBD obj = ControleGenerico.select(TipoObjetoProps.BAIRRO, campoTextoBairro.getText());
                bairro = (Bairro) obj;
                if (bairro == null) {
                    System.out.println("Falha ao recuperar do banco");
                    return false;
                } else {
                    System.out.println("Recuperado do banco com sucesso");
                }
            } else {
                System.out.println("Usuairo optou por não inserir no banco de dados.");
                return false;
            }
        } else {
            System.out.println("bairro não é nulo");
        }

        /*Se cidade for nulo será inserido no banco*/
        if (cidade == null) {
            if (mostraMensagemObjetoNulo(TipoObjetoProps.CIDADE, campoTextoCidade.getText())) {
                ControleGenerico.insert(TipoObjetoProps.CIDADE, campoTextoCidade.getText(), null);
                ObjectsBD obj = ControleGenerico.select(TipoObjetoProps.CIDADE, campoTextoCidade.getText());
                cidade = (Cidade) obj;
                if (cidade == null) {
                    System.out.println("Falha ao recuperar do banco");
                    return false;
                } else {
                    System.out.println("Recuperado do banco com sucesso");
                }
            } else {
                System.out.println("Usuairo optou por não inserir no banco de dados.");
                return false;
            }
        } else {
            System.out.println("cidade não é nulo");
        }

        /*Se estado for nulo será inserido no banco*/
        if (estado == null) {
            if (mostraMensagemObjetoNulo(TipoObjetoProps.ESTADO, campoTextoEstado.getText())) {
                ControleGenerico.insert(TipoObjetoProps.ESTADO, campoTextoEstado.getText(), null);
                ObjectsBD obj = ControleGenerico.select(TipoObjetoProps.ESTADO, campoTextoEstado.getText());
                estado = (Estado) obj;
                if (estado == null) {
                    System.out.println("Falha ao recuperar do banco");
                    return false;
                } else {
                    System.out.println("Recuperado do banco com sucesso");
                }
            } else {
                System.out.println("Usuairo optou por não inserir no banco de dados.");
                return false;
            }
        } else {
            System.out.println("estado não é nulo");
        }

        /*Se pais for nulo será inserido no banco*/
        if (pais == null) {
            if (mostraMensagemObjetoNulo(TipoObjetoProps.PAIS, campoTextoPais.getText())) {
                ControleGenerico.insert(TipoObjetoProps.PAIS, campoTextoPais.getText(), null);
                ObjectsBD obj = ControleGenerico.select(TipoObjetoProps.PAIS, campoTextoPais.getText());
                pais = (Pais) obj;
                if (pais == null) {
                    System.out.println("Falha ao recuperar do banco");
                    return false;
                } else {
                    System.out.println("Recuperado do banco com sucesso");
                }
            } else {
                System.out.println("Usuairo optou por não inserir no banco de dados.");
                return false;
            }
        } else {
            System.out.println("pais não é nulo");
        }

        /*Se pessoa for nulo será criado uma nova pessoa para posteiormente inserir no banco*/
        if (pessoa == null && opcao == CADASTRO) {
            pessoa = new Pessoas();
            pessoa.setNome(campoTextoNome.getText());
        } else {
            if (opcao == ALTERACAO) {
                return true;
            } else {
                System.out.println("pessoa não é nulo");
                JOptionPane.showMessageDialog(this, "Você não pode inserir novamente esta pessoa.\nClique em alterar caso "
                        + "deseje alterar as informações.", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                return false;
            }
        }
        return true;
    }

    private void limparTudo() {

        this.ProgressBarConexao.setValue(0);

        this.pessoa = null;
        this.logradouro = null;
        this.bairro = null;
        this.cidade = null;
        this.estado = null;
        this.pais = null;

        this.campoTextoCodigo.setText("");
        this.campoTextoNome.setText("");
        this.campoTextoLogradouro.setText("");
        this.campoTextoBairro.setText("");
        this.campoTextoCidade.setText("");
        this.campoTextoCidade.setText("");
        this.campoTextoEstado.setText("");
        this.campoTextoPais.setText("");
        conexao1.setText("");
        conexao2.setText("");
        conexao3.setText("");
        conexao4.setText("");
    }

    private boolean mostraMensagemObjetoNulo(String tabela, String valor) {

        return JOptionPane.showConfirmDialog(this, "Deseja inserir na tabela " + tabela + " as informações "
                + valor + " manualmente ?", "Atenção", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMain().setVisible(true);
            }
        });
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        campoTextoCodigo = new javax.swing.JTextField();
        campoTextoNome = new javax.swing.JTextField();
        campoTextoLogradouro = new javax.swing.JTextField();
        campoTextoBairro = new javax.swing.JTextField();
        campoTextoCidade = new javax.swing.JTextField();
        campoTextoEstado = new javax.swing.JTextField();
        campoTextoPais = new javax.swing.JTextField();
        botaoNome = new javax.swing.JButton();
        botaoLogradouro = new javax.swing.JButton();
        botaoBairro = new javax.swing.JButton();
        botaoCidade = new javax.swing.JButton();
        botaoEstado = new javax.swing.JButton();
        botaoPais = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        botaoInclusao = new javax.swing.JButton();
        botaoAlteracao = new javax.swing.JButton();
        botaoLimparCampos = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        conexao1 = new javax.swing.JLabel();
        conexao2 = new javax.swing.JLabel();
        conexao3 = new javax.swing.JLabel();
        ProgressBarConexao = new javax.swing.JProgressBar();
        conexao4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.white);
        setLocation(new java.awt.Point(0, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setLabelFor(this);
        jLabel1.setText("Cadastro de Pessoas");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Código");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.setVerifyInputWhenFocusTarget(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nome");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.setVerifyInputWhenFocusTarget(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Logradouro");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel4.setVerifyInputWhenFocusTarget(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Bairro");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel5.setVerifyInputWhenFocusTarget(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Cidade");
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel6.setVerifyInputWhenFocusTarget(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Estado");
        jLabel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel7.setVerifyInputWhenFocusTarget(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Pais");
        jLabel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel8.setVerifyInputWhenFocusTarget(false);

        campoTextoCodigo.setEditable(false);

        campoTextoLogradouro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        campoTextoBairro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        campoTextoCidade.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        campoTextoEstado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        campoTextoPais.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        botaoNome.setText("...");
        botaoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNomeActionPerformed(evt);
            }
        });

        botaoLogradouro.setText("...");
        botaoLogradouro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLogradouroActionPerformed(evt);
            }
        });

        botaoBairro.setText("...");
        botaoBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBairroActionPerformed(evt);
            }
        });

        botaoCidade.setText("...");
        botaoCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCidadeActionPerformed(evt);
            }
        });

        botaoEstado.setText("...");
        botaoEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEstadoActionPerformed(evt);
            }
        });

        botaoPais.setText("...");
        botaoPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPaisActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        botaoInclusao.setText("Inclusão");
        botaoInclusao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInclusaoActionPerformed(evt);
            }
        });

        botaoAlteracao.setText("Alteração");
        botaoAlteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlteracaoActionPerformed(evt);
            }
        });

        botaoLimparCampos.setText("Limpar");
        botaoLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparCamposActionPerformed(evt);
            }
        });

        botaoExcluir.setText("Excluir");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(botaoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoLimparCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAlteracao, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoInclusao, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botaoAlteracao, botaoExcluir, botaoInclusao, botaoLimparCampos});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(botaoInclusao, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoAlteracao, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(botaoLimparCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoExcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botaoAlteracao, botaoExcluir, botaoInclusao, botaoLimparCampos});

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        conexao1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        conexao2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        conexao3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        conexao4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(conexao1, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(conexao2, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(conexao3, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProgressBarConexao, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(conexao4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(conexao4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(conexao1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(conexao2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(conexao3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProgressBarConexao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoTextoPais, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoPais)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoTextoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botaoEstado))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoTextoLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botaoLogradouro))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoTextoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botaoBairro))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoTextoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botaoCidade))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(campoTextoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(campoTextoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botaoNome)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {campoTextoBairro, campoTextoCidade, campoTextoEstado, campoTextoLogradouro, campoTextoNome, campoTextoPais});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoTextoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(campoTextoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(campoTextoLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoLogradouro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(campoTextoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoBairro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(campoTextoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoCidade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(campoTextoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoEstado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(campoTextoPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoPais)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {campoTextoBairro, campoTextoCidade, campoTextoEstado, campoTextoLogradouro, campoTextoNome, campoTextoPais});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoLogradouroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLogradouroActionPerformed
        abreCadastroAuxiliar(TipoObjetoProps.LOGRADOURO);
    }//GEN-LAST:event_botaoLogradouroActionPerformed

    private void botaoBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBairroActionPerformed
        abreCadastroAuxiliar(TipoObjetoProps.BAIRRO);
    }//GEN-LAST:event_botaoBairroActionPerformed

    private void botaoInclusaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInclusaoActionPerformed
        if (validarCampos()) {
            if (validarObjetosNulos(CADASTRO)) {

                pessoa.setLogradouro(logradouro);
                pessoa.setBairro(bairro);
                pessoa.setCidade(cidade);
                pessoa.setEstado(estado);
                pessoa.setPais(pais);

                ControleGenerico.insert(TipoObjetoProps.PESSOAS, pessoa.getNome(), pessoa);
                JOptionPane.showMessageDialog(this, "O cadastro de " + pessoa.getNome()+" foi realizado com suceso", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                limparTudo();
            } else {
                JOptionPane.showMessageDialog(this, "Verifique as informações de cadastro\n Selecione-as do banco ou insira manualmente. ", "Atenção", JOptionPane.ERROR_MESSAGE);
                System.out.println("Objetos nulos");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Verifique os campos.", "Atenção", JOptionPane.ERROR_MESSAGE);
            System.out.println("Campo não preenchido");
        }
    }//GEN-LAST:event_botaoInclusaoActionPerformed

    private void botaoCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCidadeActionPerformed
        abreCadastroAuxiliar(TipoObjetoProps.CIDADE);
    }//GEN-LAST:event_botaoCidadeActionPerformed

    private void botaoEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEstadoActionPerformed
        abreCadastroAuxiliar(TipoObjetoProps.ESTADO);
    }//GEN-LAST:event_botaoEstadoActionPerformed

    private void botaoPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPaisActionPerformed
        abreCadastroAuxiliar(TipoObjetoProps.PAIS);
    }//GEN-LAST:event_botaoPaisActionPerformed

    private void botaoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNomeActionPerformed
        abreCadastroAuxiliar(TipoObjetoProps.PESSOAS);
    }//GEN-LAST:event_botaoNomeActionPerformed

    private void botaoLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparCamposActionPerformed
        limparTudo();
    }//GEN-LAST:event_botaoLimparCamposActionPerformed

    private void botaoAlteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlteracaoActionPerformed
        if (validarCampos()) {
            if (validarObjetosNulos(ALTERACAO)) {

                pessoa.setLogradouro(logradouro);
                pessoa.setBairro(bairro);
                pessoa.setCidade(cidade);
                pessoa.setEstado(estado);
                pessoa.setPais(pais);

                ControleGenerico.update(pessoa);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Verifique os campos.", "Atenção", JOptionPane.ERROR_MESSAGE);
            System.out.println("Campo não preenchido");
        }

        if (pessoa == null) {
            JOptionPane.showMessageDialog(this, "É preciso selecionar uma pessoa para alterar.", "Atenção", JOptionPane.ERROR_MESSAGE);
        } else {
            ControleGenerico.update(pessoa);
        }
    }//GEN-LAST:event_botaoAlteracaoActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        if (pessoa == null) {
            JOptionPane.showMessageDialog(this, "É preciso selecionar uma pessoa para excluir.", "Atenção", JOptionPane.ERROR_MESSAGE);
        } else {
            ControleGenerico.delete(pessoa);
            limparTudo();
            JOptionPane.showMessageDialog(this, "Excluido com sucesso.", "Atenção", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botaoExcluirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JProgressBar ProgressBarConexao;
    private javax.swing.JButton botaoAlteracao;
    private javax.swing.JButton botaoBairro;
    private javax.swing.JButton botaoCidade;
    private javax.swing.JButton botaoEstado;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoInclusao;
    private javax.swing.JButton botaoLimparCampos;
    private javax.swing.JButton botaoLogradouro;
    private javax.swing.JButton botaoNome;
    private javax.swing.JButton botaoPais;
    private javax.swing.JTextField campoTextoBairro;
    private javax.swing.JTextField campoTextoCidade;
    private javax.swing.JTextField campoTextoCodigo;
    private javax.swing.JTextField campoTextoEstado;
    private javax.swing.JTextField campoTextoLogradouro;
    private javax.swing.JTextField campoTextoNome;
    private javax.swing.JTextField campoTextoPais;
    public static javax.swing.JLabel conexao1;
    public static javax.swing.JLabel conexao2;
    public static javax.swing.JLabel conexao3;
    public static javax.swing.JLabel conexao4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
